# Generated by Django 4.1.7 on 2023-03-27 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accountapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HelloWorld",
        ),
    ]
